import 'package:bloc/bloc.dart';
import 'package:expense_splitter/src/feature/familia/data/model/family_expense_model.dart';
import 'familia_state.dart';
import 'package:expense_splitter/src/feature/familia/data/repository/familia_repository.dart';

class FamiliaCubit extends Cubit<FamiliaState> {
  final FamiliaRepository _repository;

  FamiliaCubit(this._repository) : super(FamiliaInitial());

  Future<void> init() async {
    await fetchFamily();
  }

  Future<void> fetchFamily() async {
    emit(FamiliaLoading());
    try {
      final familyData = await _repository.getCurrentFamily();
      if (familyData == null) {
        emit(FamiliaNoFamily());
      } else {
        final family = familyData['family'] as dynamic;
        final expenses = await _repository.fetchFamilyExpenses(family.id);

        emit(
          FamiliaLoaded(
            family: family,
            members: familyData['members'],
            expenses: expenses,
          ),
        );
      }
    } catch (e) {
      emit(FamiliaError(e.toString()));
    }
  }

  Future<void> createFamily(String name) async {
    emit(FamiliaLoading());
    try {
      await _repository.createFamily(name);
      await fetchFamily();
    } catch (e) {
      emit(FamiliaError(e.toString()));
    }
  }

  Future<void> addExpense({
    required String familyId,
    required double amount,
    String? description,
    required String category,
  }) async {
    try {
      final userId = _repository
          .authUserId; // I need to add this getter or use client directly
      if (userId == null) return;

      final expense = FamilyExpenseModel(
        id: '', // Will be generated by DB
        familyId: familyId,
        userId: userId,
        amount: amount,
        description: description,
        category: category,
        expenseDate: DateTime.now(),
        createdAt: DateTime.now(),
      );

      await _repository.addFamilyExpense(expense);
      await fetchFamily();
    } catch (e) {
      emit(FamiliaError(e.toString()));
    }
  }

  Future<void> searchMembers(String query) async {
    if (query.isEmpty) {
      emit(
        FamiliaInitial(),
      ); // Or preserve current Loaded state if we are in one
      return;
    }
    try {
      final results = await _repository.searchUsers(query);
      emit(FamiliaSearching(results));
    } catch (e) {
      emit(FamiliaError(e.toString()));
    }
  }

  Future<void> addMember(String familyId, String userId) async {
    try {
      await _repository.addMember(familyId, userId);
      await fetchFamily();
    } catch (e) {
      emit(FamiliaError(e.toString()));
    }
  }
}
