// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstd4Uo9TsG8PVo7ZK-ENz8_DE9kWCSEU',
    appId: '1:982833143438:web:adc9b4e08892cd3173b3df',
    messagingSenderId: '982833143438',
    projectId: 'shikha-b2fb0',
    authDomain: 'shikha-b2fb0.firebaseapp.com',
    storageBucket: 'shikha-b2fb0.firebasestorage.app',
    measurementId: 'G-KSREV215FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpEV0KRHZXlk4_9L0m_AJMC8ChYNn9o0',
    appId: '1:982833143438:android:a5d9ed9bc62295b673b3df',
    messagingSenderId: '982833143438',
    projectId: 'shikha-b2fb0',
    storageBucket: 'shikha-b2fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDMNNaVUaczGhzrzeswLwecFi6Miu_ANQ',
    appId: '1:982833143438:ios:b204952f8787a2b673b3df',
    messagingSenderId: '982833143438',
    projectId: 'shikha-b2fb0',
    storageBucket: 'shikha-b2fb0.firebasestorage.app',
    iosBundleId: 'com.shikha.expensesplitter.expenseSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDMNNaVUaczGhzrzeswLwecFi6Miu_ANQ',
    appId: '1:982833143438:ios:b204952f8787a2b673b3df',
    messagingSenderId: '982833143438',
    projectId: 'shikha-b2fb0',
    storageBucket: 'shikha-b2fb0.firebasestorage.app',
    iosBundleId: 'com.shikha.expensesplitter.expenseSplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCstd4Uo9TsG8PVo7ZK-ENz8_DE9kWCSEU',
    appId: '1:982833143438:web:9c9682ca5171df6c73b3df',
    messagingSenderId: '982833143438',
    projectId: 'shikha-b2fb0',
    authDomain: 'shikha-b2fb0.firebaseapp.com',
    storageBucket: 'shikha-b2fb0.firebasestorage.app',
    measurementId: 'G-FL5YWQXBW4',
  );
}
